
services:
  pg_16:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB:-postgres}
    networks:
      - oracle
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pg_16_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d

  frontend:
    depends_on:
      - api-server
    image: oracle-frontend:local
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - oracle
    environment:
      NEXT_PUBLIC_API_BASE_URL: "" # Setting this to an empty string will use current host
    env_file:
      - .env.frontend
    restart: unless-stopped

  api-server:
    depends_on:
      - pg_16
    image: oracle-backend:local
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - oracle
    restart: unless-stopped
    environment:
      ORACLE_PG_HOST: pg_16
      ORACLE_PG_PORT: 5432
      ORACLE_PG_USER: ${POSTGRES_USER:-postgres}
      ORACLE_PG_PASS: ${POSTGRES_PASSWORD:-postgres}
      ORACLE_PG_DB: ${POSTGRES_DEFAULT_DB:-oracle}
      ORACLE_OPENAI_API_KEY: ${OPENAI_API_KEY}
      ORACLE_ENABLE_ALL_TELEMETRY: ${ORACLE_API_ENABLE_ALL_TELEMETRY:-false}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
    command:
     - start_api

  mcp-server:
    depends_on:
      - pg_16
    image: oracle-backend:local
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - oracle
    restart: unless-stopped
    environment:
      ORACLE_PG_HOST: pg_16
      ORACLE_PG_PORT: 5432
      ORACLE_PG_USER: ${POSTGRES_USER:-postgres}
      ORACLE_PG_PASS: ${POSTGRES_PASSWORD:-postgres}
      ORACLE_PG_DB: ${POSTGRES_DEFAULT_DB:-oracle}
      ORACLE_OPENAI_API_KEY: ${OPENAI_API_KEY}
      ORACLE_ENABLE_ALL_TELEMETRY: ${ORACLE_MCP_ENABLE_ALL_TELEMETRY:-false}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
    command:
      - start_mcp

  enrichment-server:
    depends_on:
      - pg_16
    image: oracle-backend:local
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - oracle
    restart: unless-stopped
    environment:
      ORACLE_PG_HOST: pg_16
      ORACLE_PG_PORT: 5432
      ORACLE_PG_USER: ${POSTGRES_USER:-postgres}
      ORACLE_PG_PASS: ${POSTGRES_PASSWORD:-postgres}
      ORACLE_PG_DB: ${POSTGRES_DEFAULT_DB:-oracle}
      ORACLE_OPENAI_API_KEY: ${OPENAI_API_KEY}
    command:
      - start_enrichment

  proxy:
    depends_on:
      - frontend
      - api-server
      - mcp-server
    image: nginx:latest
    networks:
      - oracle
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  alloy:
    image: grafana/alloy:latest
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${GRAFANA_ENDPOINT}
      GRAFANA_USERNAME: ${GRAFANA_USERNAME}
      GRAFANA_PASSWORD: ${GRAFANA_PASSWORD}
    networks:
      oracle:
        aliases:
          - otel-collector
    restart: unless-stopped
    ports:
      - 4318:4318
    volumes:
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy_data:/var/lib/alloy/data

volumes:
  pg_16_data:
  alloy_data:

networks:
  oracle:
