
services:
  pg_16:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB:-postgres}
    networks:
      - oracle
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pg_16_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d

volumes:
  pg_16_data:

networks:
  oracle:
